export const routers = [
  {
    access: "read",
    isSidebarNav: true,
    component: "Card/CardList",
    layout: "Base/Base",
    group: "Catalog Management",
    name: "catalog",
    path: "/card",
    title: "Card",
    icon: "fa-tags",
  },
  {
    access: "create",
    component: "Card/CardForm",
    layout: "Base/Base",
    group: "Catalog Management",
    name: "catalog",
    path: "/card/edit",
    title: "Tambah Card",
    icon: "fa-tags",
  },
  {
    access: "update",
    component: "Card/CardForm",
    layout: "Base/Base",
    group: "Catalog Management",
    name: "catalog",
    path: "/card/edit/:id",
    title: "Edit Card",
    icon: "fa-tags",
  },
  {
    access: "read",
    isSidebarNav: true,
    component: "Section/SectionList",
    layout: "Base/Base",
    group: "Catalog Management",
    name: "catalog",
    path: "/section",
    title: "Section",
    icon: "fa-tags",
  },
  {
    access: "create",
    component: "Section/SectionForm",
    layout: "Base/Base",
    group: "Catalog Management",
    name: "catalog",
    path: "/section/edit",
    title: "Tambah Section",
    icon: "fa-tags",
  },
  {
    access: "update",
    component: "Section/SectionForm",
    layout: "Base/Base",
    group: "Catalog Management",
    name: "catalog",
    path: "/section/edit/:id",
    title: "Edit Section",
    icon: "fa-tags",
  },
  {
    access: "update",
    component: "Section/SectionOrder",
    layout: "Base/Base",
    group: "Catalog Management",
    name: "catalog",
    path: "/section/order",
    title: "Order Section",
    icon: "fa-tags",
  },
  {
    access: "read",
    isSidebarNav: true,
    component: "Menu/MenuReference/index",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/header",
    title: "Header Menu",
    icon: "fa-tasks",
  },
  {
    access: "create",
    component: "Menu/MenuForm",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/header/edit",
    title: "Tambah Header Menu",
    icon: "fa-tasks",
  },
  {
    access: "update",
    component: "Menu/MenuForm",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/header/edit/:id",
    title: "Edit Header Menu",
    icon: "fa-tasks",
  },
  {
    access: "update",
    isSidebarNav: false,
    component: "Menu/MenuOrder",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/header/order",
    title: "Order Header Menu",
    icon: "fa-tasks",
  },
  {
    access: "read",
    isSidebarNav: true,
    component: "Menu/MenuReference/index",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/hmore",
    title: "Header More",
    icon: "fa-tasks",
  },
  {
    access: "create",
    component: "Menu/MenuForm",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/hmore/edit",
    title: "Tambah Header More",
    icon: "fa-tasks",
  },
  {
    access: "update",
    component: "Menu/MenuForm",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/hmore/edit/:id",
    title: "Edit Header More",
    icon: "fa-tasks",
  },
  {
    access: "update",
    isSidebarNav: false,
    component: "Menu/MenuOrder",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/hmore/order",
    title: "Order Header More",
    icon: "fa-tasks",
  },
  {
    access: "read",
    isSidebarNav: true,
    component: "Menu/MenuReference/index",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/menu",
    title: "Menu",
    icon: "fa-tasks",
  },
  {
    access: "create",
    component: "Menu/MenuForm",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/menu/edit",
    title: "Tambah Menu",
    icon: "fa-tasks",
  },
  {
    access: "update",
    component: "Menu/MenuForm",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/menu/edit/:id",
    title: "Edit Menu",
    icon: "fa-tasks",
  },
  {
    access: "update",
    isSidebarNav: false,
    component: "Menu/MenuOrder",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/menu/order",
    title: "Order Menu",
    icon: "fa-tasks",
  },
  {
    access: "read",
    isSidebarNav: true,
    component: "Menu/MenuList",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/mmore",
    title: "Menu More",
    icon: "fa-tasks",
  },
  {
    access: "create",
    component: "Menu/MenuForm",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/mmore/edit",
    title: "Tambah Menu More",
    icon: "fa-tasks",
  },
  {
    access: "update",
    component: "Menu/MenuForm",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/mmore/edit/:id",
    title: "Edit Menu More",
    icon: "fa-tasks",
  },
  {
    access: "create",
    component: "Menu/MenuForm",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/menu/submenu/:parentId",
    title: "Tambah Submenu",
    icon: "fa-tasks",
  },
  {
    access: "update",
    component: "Menu/MenuForm",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/menu/submenu/:parentId/edit/:id",
    title: "Edit Submenu",
    icon: "fa-tasks",
  },
  {
    access: "create",
    component: "Menu/MenuForm",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/mmore/submenu/:parentId",
    title: "Tambah Submenu",
    icon: "fa-tasks",
  },
  {
    access: "update",
    component: "Menu/MenuForm",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/mmore/submenu/:parentId/edit/:id",
    title: "Edit Submenu",
    icon: "fa-tasks",
  },
  {
    access: "read",
    isSidebarNav: true,
    component: "Menu/CategoryList",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/category",
    title: "Category",
    icon: "fa-tasks",
  },
  {
    access: "create",
    component: "Menu/CategoryForm",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/category/edit",
    title: "Tambah Category",
    icon: "fa-tasks",
  },
  {
    access: "update",
    component: "Menu/CategoryForm",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/category/edit/:id",
    title: "Edit Category",
    icon: "fa-tasks",
  },
  {
    access: "update",
    isSidebarNav: false,
    component: "Menu/MenuOrder/index",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/header/order",
    title: "Order Header Menu",
    icon: "fa-tasks",
  },
  {
    access: "update",
    isSidebarNav: false,
    component: "Menu/MenuOrder/index",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/hmore/order",
    title: "Order Header More",
    icon: "fa-tasks",
  },
  {
    access: "update",
    isSidebarNav: false,
    component: "Menu/MenuOrder/index",
    layout: "Base/Base",
    group: "Menu Management",
    name: "menu",
    path: "/menu/order",
    title: "Order Menu",
    icon: "fa-tasks",
  },
  {
    access: "read",
    isSidebarNav: true,
    component: "User/UserList",
    layout: "Base/Base",
    group: "User Management",
    name: "user",
    path: "/user",
    title: "User",
    icon: "fa-id-card-o",
  },
  {
    access: "create",
    component: "User/UserForm",
    layout: "Base/Base",
    group: "User Management",
    name: "user",
    path: "/user/edit",
    title: "Tambah User",
    icon: "fa-id-card-o",
  },
  {
    access: "update",
    component: "User/UserForm",
    layout: "Base/Base",
    group: "User Management",
    name: "user",
    path: "/user/edit/:id",
    title: "Edit User",
    icon: "fa-id-card-o",
  },
  {
    access: "read",
    isSidebarNav: true,
    component: "Role/RoleList",
    layout: "Base/Base",
    group: "User Management",
    name: "role",
    path: "/role",
    title: "Role",
    icon: "fa-id-card-o",
  },
  {
    access: "create",
    component: "Role/RoleForm",
    layout: "Base/Base",
    group: "User Management",
    name: "role",
    path: "/role/edit",
    title: "Tambah Role",
    icon: "fa-id-card-o",
  },
  {
    access: "update",
    component: "Role/RoleForm",
    layout: "Base/Base",
    group: "User Management",
    name: "role",
    path: "/role/edit/:id",
    title: "Edit Role",
    icon: "fa-id-card-o",
  },
  {
    access: "read",
    isSidebarNav: true,
    component: "History/HistoryList",
    layout: "Base/Base",
    group: "User Management",
    path: "/history",
    name: "audit",
    title: "History",
    icon: "fa-id-card-o",
  },
  {
    access: "read",
    component: "History/HistoryDetail",
    layout: "Base/Base",
    group: "User Management",
    path: "/history/:id",
    name: "audit",
    title: "History",
    icon: "fa-id-card-o",
  },
  {
    access: "reminder",
    isSidebarNav: true,
    component: "PaymentReminder/Active/ReminderActive",
    layout: "Base/Base",
    group: "Payment Reminder",
    name: "Reminder",
    path: "/payment-reminder/reminder-active",
    title: "Active Reminder",
    icon: "fa-calendar-check-o",
  },
  {
    access: "reminder",
    isSidebarNav: true,
    component: "PaymentReminder/Shortcode/ShortcodeList",
    layout: "Base/Base",
    group: "Payment Reminder",
    name: "Reminder",
    path: "/payment-reminder/shortcode-list",
    title: "Shortcode",
    icon: "fa-calendar-check-o",
  },
  {
    access: "reminder",
    component: "PaymentReminder/Shortcode/ShortcodeInput",
    layout: "Base/Base",
    group: "Payment Reminder",
    name: "Reminder",
    path: "/payment-reminder/shortcode-input",
    title: "Shortcode Input",
    icon: "fa-tags",
  },
  {
    access: "reminder",
    component: "PaymentReminder/Shortcode/ShortcodeInput",
    layout: "Base/Base",
    group: "Payment Reminder",
    name: "Reminder",
    path: "/payment-reminder/shortcode-input/:id",
    title: "Shortcode Edit",
    icon: "fa-tags",
  },
  {
    access: "reminder",
    isSidebarNav: true,
    component: "PaymentReminder/Template/TemplateList",
    layout: "Base/Base",
    group: "Payment Reminder",
    name: "Reminder",
    path: "/payment-reminder/template-list",
    title: "Template",
    icon: "fa-calendar-check-o",
  },
  {
    access: "reminder",
    component: "PaymentReminder/Template/TemplateInput",
    layout: "Base/Base",
    group: "Payment Reminder",
    name: "Reminder",
    path: "/payment-reminder/template-list/template-input",
    title: "Template Input",
    icon: "fa-calendar-check-o",
  },
  {
    access: "reminder",
    component: "PaymentReminder/Template/TemplateInput",
    layout: "Base/Base",
    group: "Payment Reminder",
    name: "Reminder",
    path: "/payment-reminder/template-list/template-input/:id",
    title: "Template Input",
    icon: "fa-calendar-check-o",
  },
  {
    access: "reminder",
    isSidebarNav: true,
    component: "PaymentReminder/Transaction/TransactionList",
    layout: "Base/Base",
    group: "Payment Reminder",
    name: "catalog",
    path: "/payment-reminder/transaction-list",
    title: "Reminder",
    icon: "fa-calendar-check-o",
  },
  {
    access: "reminder",
    component: "PaymentReminder/Transaction/TransactionInput",
    layout: "Base/Base",
    group: "Payment Reminder",
    name: "Reminder",
    path: "/payment-reminder/transaction-list/transaction-input",
    title: "Transaction Input",
    icon: "fa-calendar-check-o",
  },
  {
    access: "reminder",
    component: "PaymentReminder/Transaction/TransactionInput",
    layout: "Base/Base",
    group: "Payment Reminder",
    name: "Reminder",
    path: "/payment-reminder/transaction-list/transaction-input/:id",
    title: "Transaction Input",
    icon: "fa-calendar-check-o",
  },
  {
    access: "reminder",
    isSidebarNav: true,
    component: "PaymentReminder/Reminder/ReminderList",
    layout: "Base/Base",
    group: "Payment Reminder",
    name: "Reminder",
    path: "/payment-reminder/reminder-list",
    title: "Reminder List",
    icon: "fa-calendar-check-o",
  },
  {
    access: "reminder",
    component: "PaymentReminder/Reminder/ReminderDetail",
    layout: "Base/Base",
    group: "Payment Reminder",
    name: "Reminder",
    path: "/payment-reminder/reminder-list/reminder-detail/:id",
    title: "Reminder Detail",
    icon: "fa-tags",
  },
  {
    access: "reminder",
    component: "PaymentReminder/Reminder/ReminderCustomerList",
    layout: "Base/Base",
    group: "Payment Reminder Customer List",
    name: "Reminder",
    path: "/payment-reminder/reminder-list/reminder-customer-list/:status/:id/:tid/:date",
    title: "Reminder Customer List",
    icon: "fa-tags",
  },
  {
    access: "reminder",
    component: "PaymentReminder/Reminder/ReminderInput",
    layout: "Base/Base",
    group: "Payment Reminder Input Reminder",
    name: "Reminder",
    path: "/payment-reminder/reminder-list/reminder-input/:type",
    title: "Reminder Input",
    icon: "fa-tags",
  },
  {
    access: "reminder",
    component: "PaymentReminder/Reminder/ReminderInput",
    layout: "Base/Base",
    group: "Payment Reminder Input Reminder",
    name: "Reminder",
    path: "/payment-reminder/reminder-list/edit/:id",
    title: "Edit Payment Reminder",
    icon: "fa-tags",
  },
  {
    access: "reminder",
    isSidebarNav: true,
    component: "RefundWallet/Transaction/TransactionList",
    layout: "Base/Base",
    group: "Refund Wallet",
    name: "Reminder",
    path: "/refundwallet/transaction-list",
    title: "Search Transaction",
    icon: "fa-calendar-check-o",
  },
  {
    access: "reminder",
    component: "RefundWallet/Transaction/TransactionDetail",
    layout: "Base/Base",
    group: "Refund Wallet",
    name: "Reminder",
    path: "/refundwallet/transaction-list/detail/:id",
    title: "Search Transaction Detail",
    icon: "fa-calendar-check-o",
  },
  {
    access: "reminder",
    isSidebarNav: true,
    component: "RefundWallet/History/HistoryList",
    layout: "Base/Base",
    group: "Refund Wallet",
    name: "Reminder",
    path: "/refundwallet/refund-history-list",
    title: "Refund History List",
    icon: "fa-calendar-check-o",
  },
  {
    access: "reminder",
    component: "RefundWallet/Transaction/TransactionDetail",
    layout: "Base/Base",
    group: "Refund Wallet",
    name: "Reminder",
    path: "/refundwallet/refund-history-list/detail/:id",
    title: "Refund History Detail",
    icon: "fa-calendar-check-o",
  },
  {
    access: "read",
    component: "SmartBiller/SearchTransaction/index.js",
    layout: "Base/Base",
    isSidebarNav: true,
    group: "Smart Biller",
    name: "user",
    path: "/smartbiller/search-transaction",
    title: "Search Transaction",
    icon: "fa-credit-card",
  },
  {
    access: "read",
    component: "SmartBiller/SearchTransaction/detail.js",
    layout: "Base/Base",
    group: "Smart Biller",
    name: "user",
    path: "/smartbiller/search-transaction/transaction-detail/:id",
    title: "Search Transaction",
    icon: "fa-credit-card",
  },
  {
    access: "read",
    component: "SmartBiller/Inquiry/index.js",
    layout: "Base/Base",
    isSidebarNav: true,
    group: "Smart Biller",
    name: "user",
    path: "/smartbiller/inquiry",
    title: "Inquiry",
    icon: "fa-credit-card",
  },
  {
    access: "reminder",
    isSidebarNav: true,
    component: "SmartBiller/Routings/RoutingsList",
    layout: "Base/Base",
    group: "Smart Biller",
    name: "Reminder",
    path: "/smartbiller/routings-list",
    title: "Routings",
    icon: "fa-credit-card",
  },
  {
    access: "reminder",
    component: "SmartBiller/Routings/RoutingsInput",
    layout: "Base/Base",
    group: "Smart Biller",
    name: "Reminder",
    path: "/smartbiller/routings-list/input",
    title: "Routings Input",
    icon: "fa-credit-card",
  },
  {
    access: "reminder",
    isSidebarNav: true,
    component: "SmartBiller/DenomRouting/DenomRoutingList",
    layout: "Base/Base",
    group: "Smart Biller",
    name: "Reminder",
    path: "/smartbiller/denom-routing-list",
    title: "Denom Routing",
    icon: "fa-credit-card",
  },
  {
    access: "reminder",
    component: "SmartBiller/DenomRouting/DenomRoutingInput",
    layout: "Base/Base",
    group: "Smart Biller",
    name: "Reminder",
    path: "/smartbiller/denom-routing-list/input",
    title: "Denom Routing Input",
    icon: "fa-credit-card",
  },
  {
    access: "reminder",
    component: "SmartBiller/DenomRouting/DenomRoutingInput",
    layout: "Base/Base",
    group: "Smart Biller",
    name: "Reminder",
    path: "/smartbiller/denom-routing-list/edit/:id",
    title: "Denom Routing Input",
    icon: "fa-credit-card",
  },
  {
    access: "reminder",
    component: "SmartBiller/DenomRouting/DenomRoutingDetail",
    layout: "Base/Base",
    group: "Smart Biller",
    name: "Reminder",
    path: "/smartbiller/denom-routing-list/detail/:id",
    title: "Denom Routing Detail",
    icon: "fa-credit-card",
  },

  {
    access: "read",
    isSidebarNav: true,
    component: "Settlement/SettlementList",
    layout: "Base/Base",
    name: "Settlement",
    path: "/settlement",
    title: "History Settlement List",
    icon: "fa-history",
  },
];
